### ISSUE TITLE
TypeError: cppTag.getTagType is not a function

### ISSUE THREAD

**Issue by cenotaph** [Alabate/node-freefare#5]
Running the examples/mifare_ultralight.js script, with an ultralight tag on the pn532 reader:

> Device found : pn532_uart:/dev/tty.usbserial-A505M4TB:115200
Device opened : pn532_uart:/dev/tty.usbserial-A505M4TB:115200
/Users/fail/node_modules/freefare/lib/freefare.js:122
					switch(cppTag.getTagType()) {
					              ^

> TypeError:

>  cppTag.getTagType is not a function
    at (anonymous function).listTags (/Users/fail/node_modules/freefare/lib/freefare.js:122:20)

I had some compilation warnings when installing on MacOS Sierra using homebrew for the libnfc library... warnings such as warning: '_FILE_OFFSET_BITS' macro redefined -- could this have something to do with it?

Thanks for your work, this is a great library and I'm learning....

**Comment by cenotaph** [comment]
I can report the same behaviour on a raspberry pi with the same pn532 reader. Am I doing something obviously wrong?

**Comment by Alabate** [comment]
Thank you for submitting your issue. 

I've no idea how this function can be `undefined`. And I cannot properly debug the lib because I don't have any reader with me (until end of june). So no, you're not doing wrong. I think the problem it's comming from your reader that have a different behaviour.

I've done some modifications of the lib on a different branch, to have more informations about your issue. Can you replace the `freefare` entry in your `package.json` by

```
    "freefare": "Alabate/node-freefare#bugfix/5-cppTag.getTagType"
```

Then `npm install`, try again, and give me the console ouput even if it works.

**Comment by cenotaph** [comment]
Hi! Thanks so much for your help - yeah, it seems like listTags is returning an empty hash.

Output is:

```
listTags() null [ {} ]
cppTag {}
cppTag2 {}
```

And FYI, when building the freefare module, I get these warnings (on MacOS Sierra):

```
  CXX(target) Release/obj.target/freefare/src/addon.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined
      [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/freefare.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined
      [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/device.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined
      [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/tag.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined
      [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/tag_mifareultralight.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined
      [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/tag_mifareclassic.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined
      [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
../src/tag_mifareclassic.cpp:319:27: warning: private field 'block' is not used
      [-Wunused-private-field]
        MifareClassicBlockNumber block;
                                 ^
../src/tag_mifareclassic.cpp:320:11: warning: private field 'amount' is not used
      [-Wunused-private-field]
        uint32_t amount;
                 ^
3 warnings generated.
  CXX(target) Release/obj.target/freefare/src/tag_mifaredesfire.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined
      [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  SOLINK_MODULE(target) Release/freefare.node
```

Also, libNFC 1.7.1 seems to work fine with the same card on the reader:

```
$ mifare-ultralight-info
Tag with UID 04546cc2d34881 is a Mifare UltraLight
```

```
$ nfc-poll
nfc-poll uses libnfc 1.7.1
NFC reader: pn532_uart:/dev/tty.usbserial-A505M4TB opened
NFC device will poll during 30000 ms (20 pollings of 300 ms for 5 modulations)
ISO/IEC 14443A (106 kbps) target:
    ATQA (SENS_RES): 00  44
       UID (NFCID1): 04  54  6c  c2  d3  48  81
      SAK (SEL_RES): 00
nfc_initiator_target_is_present: Target Released
Waiting for card removing...done.
```

and your freefare module is definitely finding the reader OK cause I'm logging that after it's opened:

`opened pn532_uart:/dev/tty.usbserial-A505M4TB:115200`

Let me know if there's anything else I can try or if you want to chat directly....

**Comment by Alabate** [comment]
About the warnings, it's seems to be ok, i've got the same.

I tried to add some random debug messages into the C++ code. Can you do `npm install freefare`, and try again ?

**Comment by cenotaph** [comment]
Amazing!

It won't build - I get:

```
In file included from ../src/device.h:13:
../src/tag.h:22:23: error: unknown type name 'FreefareTag'; did you mean
      'freefare_tag'?
    void (*free_tag) (FreefareTag tag);
                      ^~~~~~~~~~~
                      freefare_tag
../src/tag.h:17:8: note: 'freefare_tag' declared here
struct freefare_tag {
       ^
1 warning and 1 error generated.
make: *** [Release/obj.target/freefare/src/addon.o] Error 1
```

**Comment by Alabate** [comment]
You seem to have an older version of Freefare C librairy. Can you give me the version number of your Freefare lib ?

I've updated the branch, can you try again ?

**Comment by cenotaph** [comment]
Great!

```
$ node examples/mifare_ultralight.js
Device found : pn532_uart:/dev/tty.usbserial-A505M5AU:115200
Device opened : pn532_uart:/dev/tty.usbserial-A505M5AU:115200
libnfc_context:0x10286a600
count:0:0x102502180
instanciate i:0
instanciate hello 1
instanciate hello 2
instanciate hello 3
New hello 1
New hello ConstructCall 1
New hello ConstructCall 2
listTags() null [ {} ]
cppTag {}
cppTag2 {}
/Users/fail/src/newkiosk/node_modules/freefare/lib/freefare.js:129
						switch(cppTag.getTagType()) {
						              ^

TypeError: cppTag.getTagType is not a function
    at (anonymous function).listTags (/Users/fail/src/newkiosk/node_modules/freefare/lib/freefare.js:129:21)
```

libfreefare 0.4.0_1 is installed via homebrew. I wonder if somehow npm is compiling your module against an older library? I can't seem to find another one anywhere else.

**Comment by danfalk** [comment]
I'm running into the exact same issue with a Beaglebone, Debian and pn532 via UART.   In my case I'm running mifare_classic.js.

Any new ideas?  Thanks.

**Comment by CoryKniefel** [comment]
I'm having same issue. I notice you use "libfreefare-dev" and I wondered if using that would solve the issue. Unfortunately, I'm having issues installing the dev version locally. Do you think that using the dev version of freefare would solve the issue?

**Comment by Alabate** [comment]
I dont think, but I don't really know because I didn't manage to find the problem.

I'm really sorry, but I can not help you all on this problem currently, because I don't have any compatible reader and cards with me. We tried to do a lot of *remote* tests with cenotaph (thank you cenotaph for this), but unfortunately, that didn't help me.

I will try to get a compatible reader for the end of may. Before that, I don't have any solution for you :/

**Comment by cenotaph** [comment]
I have a spare Pn532 board that you can pop an FTDI adapter on and easily use with libusb - Alabate, do you want me to post it to you? You can just send it back to me when you're finished. Or is that a ridiculous idea? :)

**Comment by CoryKniefel** [comment]
I appreciate your concern :) If anyone can recommend a good module for libnfc compatible chips, I'd very much appreciate it. I'm using Mac, and can't find anything that will work. And I know zero c++ so I'm pretty stuck.

**Comment by Alabate** [comment]
@cenotaph Thank you for this offer, but I think it will cost you a lot and don't really trust the post here. I'm currently in hungary and without speaking hungarian it's not easy to look for lost packages. I will go back to france for 20 of may and I will try to borrow a PN532 device from a friend or from my university. Thank you again for the offer !

@CoryKniefel You can find some other lib, but I think you can only read UID with them. That's why I made this lib. You can maybe try to find another library in other languages like python or ruby.

**Comment by Alabate** [comment]
No good news yet, but just to keep you updated, I managed to get a PN532 device, I did some test via uart and I didn't manage to trigger the bug. But I did it from Archlinux. I will do it from debian or resbian in few days.

**Comment by CoryKniefel** [comment]
Thanks for the update. I'm not sure if I mentioned this above, but I am
using OS X El Capitan. I currently have a workaround... but would love to
see this working. Cheers!

**Comment by Alabate** [comment]
@CoryKniefel Yes but danfalk also had the same error under debian (and its easier to test on debian as I don't have any mac)

So I managed to trigger the same error under debian and it was a v8 scope issue. It should be fixed now with 0.1.5. Thank you everyone for your help and for your patience :)

**Comment by danfalk** [comment]
Thanks for the fix!  I'll try it out as soon as I can and let you know if I'm still having any issues.
